
image: cypress/base:12.14.0

variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/.cache/cypress"
  npm_config_cache: "$CI_PROJECT_DIR/.cache/npm"

stages:
  - install
  - test

install:
  stage: install
  script:
    - npm install
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules

cypress:
  stage: test
  script:
    - npx cypress install
    - npm run record
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
