name: Test
on:
  push:
    branches: [main, develop]
    tags: ['**']
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    name: Test with Cypress
    runs-on: ubuntu-20.04
    steps:
      - name: Get the latest pnpm version
        id: pnpm
        run: echo "::set-output name=latest-version::$(npm show pnpm version)"
        shell: bash
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ steps.pnpm.outputs.latest-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
#      - name: Install dependencies
#        run: pnpm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: pnpm install
          start: pnpm sandbox
          wait-on: 'http://localhost:8080'
